### ISSUE TITLE
Use tools for Psalm, etc.

### ISSUE THREAD

**Issue by arogachev** [yiisoft/actions#50]
https://github.com/marketplace/actions/setup-php-action#wrench-tools-support

**Comment by samdark** [comment]
Alright. But how to run these locally then?

**Comment by terabytesoftw** [comment]
If we remove psalm, rector, phpunit, and tools as dev dependencies, drawbacks:

1.- Users will have to install everything for local execution.
2.- We will not be in the latest version of the package.
3.- If the package has a defective version, we cannot control the version to install.

Ultimately, in my opinion, there is no difference.
